---
- name: Deploy Nginx server with custom configuration
  hosts: nginx_servers
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: true

    - name: Copy customized Nginx configuration template
      template:
        src: templates/nginx.conf.j2  # Path to your Jinja template file
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
